### ISSUE TITLE
inline-images is not BC because gulp-image-data-uri is not installed 

### ISSUE THREAD

**Issue by Arjen-Smit** [ConnectHolland/gulp-tasks#7]
The inline-images task breaks projects that don't have the gulp-image-data-uri installed.

This can most likely be fixed when using the plugin versions of the plugins instead of defining them in the task.

**Comment by Arjen-Smit** [comment]
Current error when running gulp without gulp-image-data-uri installed

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp-image-data-uri'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/srv/www/sources/sigravitaliteitshuis/var/frontend/bower_components/gulp-tasks/tasks/inline-images.js:7:24)
    at createTask (/srv/www/sources/sigravitaliteitshuis/var/frontend/node_modules/gulp-simple-task-loader/build/processor.js:57:43)
    at handleFileOrDirectory (/srv/www/sources/sigravitaliteitshuis/var/frontend/node_modules/gulp-simple-task-loader/build/processor.js:52:13)
    at Array.forEach (native)
    at processDirectory (/srv/www/sources/sigravitaliteitshuis/var/frontend/node_modules/gulp-simple-task-loader/build/processor.js:73:67)
    at Object.processTaskDirectory (/srv/www/sources/sigravitaliteitshuis/var/frontend/node_modules/gulp-simple-task-loader/build/processor.js:76:7)
```
